name: praktikertjanst
description: Portal for praktikertj√§nst
version: 0.0.1
author: dmarl <dmarlovic83@gmail.com>
environment:
  sdk: ">=2.2.1-dev.3.0 <3.0.0"
dependencies:
  angular_router: ^2.0.0-alpha+23
  d_components:
    git: https://github.com/afpatmin/d_components
  grid_css: ^0.1.1
  intl: ^0.15.8
  http: ^0.12.0+2
  fo_components: ^1.3.0
  angular_components: 0.14.0-alpha
  angular: 6.0.0-alpha
dev_dependencies:
  sass_builder: ^2.1.3
  intl_translation: ^0.17.5
  build_runner: ^1.5.1
  build_web_compilers: ^2.1.0
